### ISSUE TITLE
Some CSS characters are escaped

### ISSUE THREAD

**Issue by greatislander** [mirisuzanne/remedocs#6]
I was taking a look at this as an inspiration for documenting a CSS project of my own and I noticed that in some cases certain characters in CSS code blocks are escaped by Eleventy, for example:

```css
[type=&#39;checkbox&#39;],
[type=&#39;radio&#39;] {
  box-sizing: border-box;
  padding: 0;
}
```

This can be addressed by changing this line:

https://github.com/mirisuzanne/remedocs/blob/b4c12adcc4b045b5edac0d62ea165cf4330e3132/src/_includes/doxray.njk#L36

To:

```nunjucks
    {% highlight "css" %}{{ css | safe }}{% endhighlight %}
```

I'd be happy to open a PR to address this if you'd like. Thanks for your work on this project!
